services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: ts-example.db
    volumes:
      - ./../../pgdata:/var/lib/postgresql/data
    ports:
      - '5444:5432' # external:internal

  app:
    build:
      context: ./../../
      dockerfile: ./etc/docker/Dockerfile
    container_name: ts-example.app
    ports:
      - '3111:3000' # external:internal
    depends_on:
      - db
    volumes:
      - ./../../:/src  # Mount everything
      - /src/node_modules  # Keep node_modules inside the container
    command: npm run start:dev  # Override default CMD in Dockerfile

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: ts-example.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '8111:80' # external:internal
    depends_on:
      - db